/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.sun.xml.internal.ws.api.model.wsdl.editable.EditableWSDLPart;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AlumnoDialogo extends javax.swing.JDialog {
    
    private ModalResult modalResult;
    private ArrayList <Alumno> alumno;
    private int num;
    /**
     * Creates new form AlumnoDialogo
     */
    public AlumnoDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private double validarCalificacion() throws CalificacionException{
        double cal = -1;
        try{
            cal = Double.valueOf(edtCalificacion.getText());
            if ((cal < 0.0) || (cal > 10.0)){
                throw new CalificacionException();
            }
            return cal;
        }catch(Exception e){
            throw new CalificacionException("Hubo un erro en la calificacion");
        }
    }
    
    private String validarNombre() throws NombreException{
        if ("".equals(edtNombre.getText())){
            throw new NombreException("No hay nada en nombre");
            
        }
        return "Si";
    }
    
    private String validarPaterno() throws PaternoException{
        if ("".equals(edtPaterno.getText())){
            throw new PaternoException("No hay nada en el apellido paterno");
        }
        return "Si";
    }
    
    private String validarMaterno() throws MaternoException{
        if ("".equals(edtMaterno.getText())){
            throw new MaternoException("No hay nada en el apellido materna");
        }
        return "Si";
    }
    
    private Integer validarCarrera() throws CarreraException{
        int num = cmbCarrera.getSelectedIndex();
        if(num < 0){
            throw new CarreraException("No ha seleccionada una carrera");
        }
        return num;
    }
    
    private String validarMatricula() throws MatriculaException{
        int n = edtMatricula.getText().length();
        
        if ("".equals(edtMatricula.getText())){
            throw new MatriculaException("No hay nada en la matrícula");
        }
        
        if (n < 9){
            throw new MatriculaException("La matrícula debe incluir 9 caracteres");
        }
        
        if (n > 9){
            throw new MatriculaException("La matrícula solo debe incluir 9 caracteres");
        }
        
        for (int i = 0; i < alumno.size(); i++){
            if (alumno.get(i).getMatricula().equals(edtMatricula.getText())){
                throw new MatriculaException("Esta matrícula ya existe");
            }
        }
        return "Si";
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNombre = new javax.swing.JTextField();
        edtPaterno = new javax.swing.JTextField();
        edtMaterno = new javax.swing.JTextField();
        edtCalificacion = new javax.swing.JTextField();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        edtMatricula = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 13))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("A. Paterno:");

        jLabel3.setText("A. Materno:");

        jLabel4.setText("Carrera:");

        jLabel5.setText("Calificación:");

        edtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNombreActionPerformed(evt);
            }
        });

        cmbCarrera.setModel(new DefaultComboBoxModel(Carrera.values()));

        jLabel6.setText("Matricula");

        edtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edtMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtCalificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try{
            if (num == 0){
                String matricula = validarMatricula();
            }
            
            String nombre = validarNombre();
            String paterno = validarPaterno();
            String materno = validarMaterno();
            double cal = validarCalificacion();
            validarCarrera();
            
            Alumno alumno = new Alumno(
                edtNombre.getText(),
                edtPaterno.getText(),
                edtMaterno.getText(),
                edtMatricula.getText(),
                Double.valueOf(edtCalificacion.getText()),
                (Carrera)cmbCarrera.getSelectedItem()
            );
            modalResult = ModalResult.ACEPTAR;
            this.setVisible(false);
        }catch(CalificacionException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            edtCalificacion.requestFocus();
        } catch (PaternoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            edtPaterno.requestFocus();
        } catch (MaternoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            edtMaterno.requestFocus();
        } catch (NombreException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            edtNombre.requestFocus();
        } catch (CarreraException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            edtNombre.requestFocus();
        } catch (MatriculaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            edtMatricula.requestFocus();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        modalResult = ModalResult.CANCELAR;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMatriculaActionPerformed

    private void edtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public ModalResult mostrarDialogo(ArrayList <Alumno> alumno){
        this.alumno = alumno;
        num = 0;
        modalResult = ModalResult.CANCELAR;
        edtMatricula.setEditable(true);
        edtNombre.setText("");
        edtPaterno.setText("");
        edtMaterno.setText("");
        edtMatricula.setText("");
        edtCalificacion.setText("");
        cmbCarrera.setSelectedIndex(-1);
        this.setVisible(true);
        return modalResult;
    }
    
    public ModalResult mostrarAlumno(Alumno modificar){
        num = 1;
        modalResult = ModalResult.CANCELAR;
        edtNombre.requestFocus();
        edtNombre.setText(modificar.getNombre());
        edtPaterno.setText(modificar.getPaterno());
        edtMaterno.setText(modificar.getMaterno());
        edtMatricula.setText(modificar.getMatricula());
        edtMatricula.setEditable(false);
        edtCalificacion.setText(modificar.getCalificacion().toString());
        cmbCarrera.setSelectedIndex(numeroCarrera(modificar.getCarrera()));
        this.setVisible(true);
        return modalResult;
    }
    
    private Integer numeroCarrera(Carrera carrera){
        int numero = -1;
        if(Carrera.ELECTRONICA == carrera){
            numero = 0;
        }
        if(Carrera.ARQUITECTURA == carrera){
            numero = 1;
        }
        if(Carrera.DERECHO == carrera){
            numero = 2;
        }
        if(Carrera.FISIOTERAPIA == carrera){
            numero = 3;
        }
        if(Carrera.MEDICINA == carrera){
            numero = 4;
        }
        
        return numero;
    }
    
    public Alumno getAlumno(){
        
        Alumno alumno = new Alumno(
                edtNombre.getText(),
                edtPaterno.getText(),
                edtMaterno.getText(),
                edtMatricula.getText(),
                Double.valueOf(edtCalificacion.getText()),
                (Carrera)cmbCarrera.getSelectedItem()
        );
        return alumno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JTextField edtCalificacion;
    private javax.swing.JTextField edtMaterno;
    private javax.swing.JTextField edtMatricula;
    private javax.swing.JTextField edtNombre;
    private javax.swing.JTextField edtPaterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
